<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FactTestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $facts = [
            [
                'date' => '2021-01-31',
                'code_id' => 1,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 1000,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 2,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 1000,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 3,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 1000,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 4,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 1000,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 5,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 1000,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 6,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 1000,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 7,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 1000,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 8,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 1000,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 9,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 1000,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 10,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 1000,
            ],
            //-------------------------------------
            [
                'date' => '2021-01-31',
                'code_id' => 11,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 1000,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 12,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 1000,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 13,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 1000,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 14,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 1000,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 15,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 1000,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 16,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 1000,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 17,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 18,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 19,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 20,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            //-------------------------------------
            [
                'date' => '2021-01-31',
                'code_id' => 21,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 22,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 23,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 24,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 25,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 26,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 27,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 28,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 29,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 30,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            //-------------------------------------
            [
                'date' => '2021-01-31',
                'code_id' => 31,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 32,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 33,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 34,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 35,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 36,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 37,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 38,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 39,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 40,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            //-------------------------------------
            [
                'date' => '2021-01-31',
                'code_id' => 41,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 42,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 43,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 44,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 45,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 46,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 47,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 48,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 49,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 50,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            //-------------------------------------
            [
                'date' => '2021-01-31',
                'code_id' => 51,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 52,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 53,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 54,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 55,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 56,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 57,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 58,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 59,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 60,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            //-------------------------------------
            [
                'date' => '2021-01-31',
                'code_id' => 61,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 62,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 63,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 64,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 65,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 66,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 67,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 68,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 69,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 70,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            //-------------------------------------
            [
                'date' => '2021-01-31',
                'code_id' => 71,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 72,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 73,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 74,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 75,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 76,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 77,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 78,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 79,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 80,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            //-------------------------------------
            [
                'date' => '2021-01-31',
                'code_id' => 81,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 82,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 83,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 84,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 85,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 86,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 87,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 88,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 89,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 90,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            //-------------------------------------
            [
                'date' => '2021-01-31',
                'code_id' => 91,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 92,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 93,
                'report_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => -10,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 94,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 95,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 96,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 97,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 98,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 99,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 100,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            //-------------------------------------
            [
                'date' => '2021-01-31',
                'code_id' => 101,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 102,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 103,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 104,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 105,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 106,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 107,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 108,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 109,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 110,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            //-------------------------------------
            [
                'date' => '2021-01-31',
                'code_id' => 111,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 112,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 113,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 114,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 115,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 116,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 117,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 118,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 119,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 120,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            //-------------------------------------
            [
                'date' => '2021-01-31',
                'code_id' => 121,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 122,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 123,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 124,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 125,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 126,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 127,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 128,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 129,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 130,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            //-------------------------------------
            [
                'date' => '2021-01-31',
                'code_id' => 131,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 132,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 133,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 134,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 135,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 136,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 137,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 138,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 139,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 140,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            //-------------------------------------
            [
                'date' => '2021-01-31',
                'code_id' => 141,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 142,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 143,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 144,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 145,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 146,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 147,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 148,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 149,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 150,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            //-------------------------------------
            [
                'date' => '2021-01-31',
                'code_id' => 151,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 152,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 153,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 154,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 155,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 156,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 157,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 158,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 159,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 160,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            //-------------------------------------
            [
                'date' => '2021-01-31',
                'code_id' => 161,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 162,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 163,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 164,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ],
            [
                'date' => '2021-01-31',
                'code_id' => 165,
                'report_id' => 3,
                'company_id' => 1,
                'user_id' => 1,
                'amount' => 100,
            ]
        ];

        DB::table('facts')->insert($facts);
    }
}
